import LoginModal from "@/components/modals/login-modal";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import RegisterModal from "@/components/modals/register-modal";
import { Toaster } from "react-hot-toast";
import { NextAuthProvider } from "./providers";
import EditModal from "@/components/modals/edit-modal";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <Toaster />
        <LoginModal />
        <RegisterModal />
        <EditModal />
        <NextAuthProvider>{children}</NextAuthProvider>
      </body>
    </html>
  );
}
